// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/example/nunu-saas-template/internal/app"
	"github.com/example/nunu-saas-template/internal/config"
	"github.com/example/nunu-saas-template/internal/handler"
	"github.com/example/nunu-saas-template/internal/logging"
	"github.com/example/nunu-saas-template/internal/observability"
	"github.com/example/nunu-saas-template/internal/platform/cache"
	"github.com/example/nunu-saas-template/internal/platform/database"
	"github.com/example/nunu-saas-template/internal/server"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func New(contextContext context.Context, configConfig config.Config) (*app.App, func(), error) {
	logger, cleanup, err := logging.New(configConfig)
	if err != nil {
		return nil, nil, err
	}
	mySQL, cleanup2, err := database.OpenMySQL(contextContext, configConfig, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	client, cleanup3, err := cache.OpenRedis(contextContext, configConfig, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	health := newHealth(mySQL, client)
	metrics := newMetrics(configConfig)
	http := server.NewHTTP(configConfig, logger, health, metrics)
	appApp := app.New(http, logger)
	return appApp, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func newHealth(mysql *database.MySQL, redisClient *redis.Client) *handler.Health {
	checks := []handler.DependencyCheck{
		{Name: "mysql", Check: mysql.SQL.PingContext},
	}
	if redisClient != nil {
		checks = append(checks, handler.DependencyCheck{
			Name: "redis",
			Check: func(ctx context.Context) error {
				return redisClient.Ping(ctx).Err()
			},
		})
	}
	return handler.NewHealth(checks...)
}

func newMetrics(cfg config.Config) *observability.Metrics {
	return observability.NewMetrics(cfg.Name)
}
